config/routes.rb
Rails.application.routes.draw do
  get 'error/index'
  get 'profile/profile'
  post 'profile_update', to: 'profile#profile_update', as: :profile_update


  mount Notifications::Engine => "/notifications"


  get 'seller_dashboard/index'
  get 'seller_dashboard/orders'
  
  resources :carts, only: [:index]
  get 'add_to_cart/:product_id', to: 'carts#add_to_cart', as: 'add_to_cart'
  patch 'update_quantity/:id', to: 'carts#update_quantity', as: 'update_quantity'
  get 'remove_from_cart/:id', to: 'carts#remove_from_cart', as: 'remove_from_cart'
  post 'checkout', to: 'carts#checkout', as: 'checkout'


  resources :products do
    post 'review', on: :member, to: 'products#create_review'
  end

  get 'my_question/index'
  resources :live_feeds do
    resources :answers
  end



  resources :live_feeds do
    member do
      get "like" => "live_feeds#like"
      get "likes" => "live_feeds#likes"

    end
  end


  get 'my_questions/question'
  root to: "home#index"
  post '/home/send_location', to: 'home#send_location'


  devise_for :user, controllers:{ registrations:'user/registrations'}

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :live_feed ,  foreign_key: "live_feed_id" 
  belongs_to :user

  after_commit :create_notification, on: :create

  private
  
  def create_notification
    Notification.create do |notification|
      notification.notify_type = 'post'
      notification.actor = self.user
      notification.user=self.live_feed.user
      notification.target=self
      notification.second_target= self.live_feed
    end
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    belongs_to :product
    has_many :cart_items
  end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :live_feed
end

app/models/live_feed.rb
class LiveFeed < ApplicationRecord
    has_many :answers, dependent: :destroy
    has_many :likes, dependent: :destroy
    belongs_to :user
    has_one_attached :post_image
    acts_as_votable
    
    validates :post_image, presence: true
    validates :question_body, presence: true, length: { minimum: 10 }

    after_create_commit { broadcast_prepend_to 'live_feed_channel', target: 'live_feeds' }
    
end

app/models/notification.rb
# Auto generate with notifications gem.
class Notification < ActiveRecord::Base
  include Notifications::Model

  # Write your custom methods...
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy
  validates :address, presence: true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product 
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_one_attached :product_image
  has_many :carts , dependent: :destroy
  has_many :order_items, dependent: :destroy
  has_many :reviews, dependent: :destroy


  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "price", "product_description", "product_name", "quantity", "updated_at", "user_id"]
  end
  
end

app/models/profile_image.rb
class ProfileImage < ApplicationRecord
    belongs_to :user
    has_one_attached :image
  end
  

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user
  end
  

app/models/user.rb
class User < ApplicationRecord
  has_many :live_feeds
  has_many :products , dependent: :destroy
  has_many :carts
  has_many :orders, dependent: :destroy
  has_one :profile_image, dependent: :destroy
  has_many :reviews
  acts_as_voter


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



         validates :mobile, phone: { possible: true, allow_blank: true, types: [:voip, :mobile], country_specifier: -> (phone) { 'IN' } }

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index  
        @cart2={
          image_path:"notification.png",
          title:"Notifications",
          background:"#A195EB"
        }
  
        @cart3={
          image_path:"stream.png",
          title:"Live Feed",
          background:"#9D97C2"
        }
  
        @cart4={
          image_path:"online-shopping.png" ,
          title:"Online Store",
          background:"#7DEC3B7"
        }
  end

  def send_location
    latitude = params[:latitude]
    longitude = params[:longitude]

    session[:latitude] = latitude
    session[:longitude] = longitude
    
    render json: { status: 'success' }
  end
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/error_helper.rb
module ErrorHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/learning_helper.rb
module LearningHelper
end

app/helpers/live_feeds_helper.rb
module LiveFeedsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/home/_cart.html.erb
<%= stylesheet_link_tag "home" %>

<%# <%= link_to login_path do %> 
  <div class="cart">
    <%= image_tag acc_data[:image_path], alt: "Image" %>
    <h3><%= acc_data[:title] %></h3>
  </div>
<%# <% end %> 

app/views/home/index.html.erb
<%= stylesheet_link_tag "home" %>

    <div class="body" style="top:0; position:absolute;">
    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="container">

          <div class="inner cover">
            <h1 class="cover-heading">Welocome To AgriLink</h1>
            <p class="lead">AgriLink is a revolutionary platform dedicated to transforming agriculture for a sustainable tomorrow. It serves as a dynamic hub where farmers, students, sellers, and companies converge to foster innovation and growth in the agricultural sector.</p>
            <p class="lead">
              <a href="#about" class="btn btn-lg btn-default link">Learn more</a> <% if !user_signed_in?%> <%= link_to "Register", new_user_registration_path,class:"btn btn-lg btn-default link" %> <% end %>
            </p>
          </div>

        </div>

      </div>

    </div>

  <h2 class="feature-head">Features</h2>

  <div class="featurs">

    <%= link_to notifications_path , class:'link' do %>
  <%= render "cart", acc_data: @cart2 %>
    <% end %>
    <%= link_to  live_feeds_path , class:'link' do %>
  <%= render "cart", acc_data: @cart3 %>
    <% end %>

    <%= link_to products_path  , class:'link' do %>
  <%= render "cart", acc_data: @cart4 %>
    <% end %>

    </div>


    <div class="about" id="about">
    <h2>About Us:</h2>
    <p class="about-text">Welcome to AgriLink, your comprehensive platform for revolutionizing the agriculture sector! At AgriLink, we've developed a dynamic ecosystem that connects farmers, agricultural experts, and suppliers to foster growth, innovation, and sustainability in farming practices.

Our journey began with a vision to bridge the gap between technology and agriculture, empowering farmers with digital tools to enhance productivity and profitability. AgriLink is the brainchild of our team at Ackrity Computing, conceived as part of our commitment to driving positive change through technological innovation.</p>
    
    <div>
<h4>Key Features of AgriLink:</h4>

<p><strong>Expert Advice</strong>: Have a question about crop management, pest control, or soil health? Our platform allows users to seek guidance from seasoned agricultural experts, ensuring informed decision-making every step of the way.</p>
<p><strong>Marketplace</strong>: Looking to buy fertilizers, seeds, or other agricultural inputs? AgriLink offers a convenient marketplace where users can browse a wide range of products, compare prices, and make purchases hassle-free.</p>
<p><strong>Farmers' Market</strong>: For farmers looking to sell their produce, AgriLink provides a dedicated marketplace where they can showcase their products to a wider audience, facilitating fair trade and equitable market access.</p>
<p><strong>Community Engagement</strong>: Connect with like-minded individuals, join discussions, and share insights within our vibrant farming community. AgriLink fosters collaboration and knowledge exchange to foster continuous learning and growth.</p>
<p>Built with Ruby on Rails: Our platform is powered by robust technology, leveraging the flexibility and scalability of Ruby on Rails to deliver a seamless user experience.
Join us in transforming the agriculture sector one innovation at a time. Whether you're a seasoned farmer, an agricultural enthusiast, or a supplier looking to contribute to sustainable farming practices, AgriLink is your ultimate destination.</p>

Let's cultivate a brighter future for agriculture together!</div>


    </div>

    <div class="contact">
    <h2>Contact Us:</h2>

   <p> Thank you for your interest in AgriLink! We're here to assist you with any inquiries, feedback, or support you may need. Please feel free to reach out to us using the information below:<p>
  <div class="contact-field"> <p> <strong>Address: At. Post Akot, 444101</strong></p>
<p><strong>Phone: 9370260424 </strong></p>
<p><strong>Email: pratikingle66@gmail.com</strong></p>
</div>
<p>We value your feedback and strive to provide exceptional service to our community. Your input helps us continually improve AgriLink and deliver meaningful solutions to the agriculture sector.</p>

<p>Thank you for choosing AgriLink. We look forward to hearing from you!</p>
    </div>
    </div>

<script>
document.addEventListener("DOMContentLoaded", function() {
  getLocation();
});

function getLocation() {
  if (navigator.geolocation) {
    const position=navigator.geolocation.getCurrentPosition();
    sendLocation(position);
  } else {
    alert("Geolocation is not supported by this browser.");
  }
}

function sendLocation(position) {
  const latitude = position.coords.latitude;
  const longitude = position.coords.longitude;
  const authenticityToken = document.querySelector("meta[name=csrf-token]").content;

  sendToController(latitude, longitude, authenticityToken);
}

function sendToController(latitude, longitude, token) {

  const req = new XMLHttpRequest();

  req.open("POST", "/home/send_location", true);
  req.setRequestHeader("Content-Type", "application/json");
  req.setRequestHeader("X-CSRF-Token", token);


  const data = JSON.stringify({
    latitude: latitude,
    longitude: longitude
  });

  req.send(data);
}



</script>