config/routes.rb
Rails.application.routes.draw do
  get 'error/index'
  get 'profile/profile'
  post 'profile_update', to: 'profile#profile_update', as: :profile_update


  mount Notifications::Engine => "/notifications"


  get 'seller_dashboard/index'
  get 'seller_dashboard/orders'
  
  resources :carts, only: [:index]
  get 'add_to_cart/:product_id', to: 'carts#add_to_cart', as: 'add_to_cart'
  patch 'update_quantity/:id', to: 'carts#update_quantity', as: 'update_quantity'
  get 'remove_from_cart/:id', to: 'carts#remove_from_cart', as: 'remove_from_cart'
  post 'checkout', to: 'carts#checkout', as: 'checkout'


  resources :products do
    post 'review', on: :member, to: 'products#create_review'
  end

  get 'my_question/index'
  resources :live_feeds do
    resources :answers
  end



  resources :live_feeds do
    member do
      get "like" => "live_feeds#like"
      get "likes" => "live_feeds#likes"

    end
  end


  get 'my_questions/question'
  root to: "home#index"
  post '/home/send_location', to: 'home#send_location'


  devise_for :user, controllers:{ registrations:'user/registrations'}

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :live_feed ,  foreign_key: "live_feed_id" 
  belongs_to :user

  after_commit :create_notification, on: :create

  private
  
  def create_notification
    Notification.create do |notification|
      notification.notify_type = 'post'
      notification.actor = self.user
      notification.user=self.live_feed.user
      notification.target=self
      notification.second_target= self.live_feed
    end
end
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    belongs_to :product
    has_many :cart_items
  end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :live_feed
end

app/models/live_feed.rb
class LiveFeed < ApplicationRecord
    has_many :answers, dependent: :destroy
    has_many :likes, dependent: :destroy
    belongs_to :user
    has_one_attached :post_image
    acts_as_votable
    
    validates :post_image, presence: true
    validates :question_body, presence: true, length: { minimum: 10 }

    after_create_commit { broadcast_prepend_to 'live_feed_channel', target: 'live_feeds' }
    
end

app/models/notification.rb
# Auto generate with notifications gem.
class Notification < ActiveRecord::Base
  include Notifications::Model

  # Write your custom methods...
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy
  validates :address, presence: true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product 
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_one_attached :product_image
  has_many :carts , dependent: :destroy
  has_many :order_items, dependent: :destroy
  has_many :reviews, dependent: :destroy


  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "price", "product_description", "product_name", "quantity", "updated_at", "user_id"]
  end
  
end

app/models/profile_image.rb
class ProfileImage < ApplicationRecord
    belongs_to :user
    has_one_attached :image
  end
  

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user
  end
  

app/models/user.rb
class User < ApplicationRecord
  has_many :live_feeds
  has_many :products , dependent: :destroy
  has_many :carts
  has_many :orders, dependent: :destroy
  has_one :profile_image, dependent: :destroy
  has_many :reviews
  acts_as_voter


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



         validates :mobile, phone: { possible: true, allow_blank: true, types: [:voip, :mobile], country_specifier: -> (phone) { 'IN' } }

end

app/controllers/seller_dashboard_controller.rb
class SellerDashboardController < ApplicationController
  def index
    @products = current_user.products
  end

  def products
    @products = current_user.products
  end

  def orders
    @orders = OrderItem.where(seller_id: current_user.id).map(&:order).uniq
  end
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/error_helper.rb
module ErrorHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/learning_helper.rb
module LearningHelper
end

app/helpers/live_feeds_helper.rb
module LiveFeedsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/seller_dashboard_helper.rb
module SellerDashboardHelper
end

app/views/seller_dashboard/index.html.erb
<h1 class="cart-head">Welcome to Your Seller Dashboard</h1>
<div class="seller-link">
<%= link_to 'Orders', seller_dashboard_orders_path,class:"link seller-prod" %>
</div>
<h1>Your Listed Products</h1>
<% if @products.any? %>
  <table id="customers">
    <thead>
      <tr>
        <th>Produvt Id</th>
        <th>Product Name</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.id %></td>
          <td><%= product.product_name %></td>
          <td><%= number_to_currency(product.price, unit: '₹', precision: 2) %></td>
          <td><%=  product.quantity %></td>
          <td style="display:flex; aline-items:center; justify-content:center">
            <%= link_to 'Edit', edit_product_path(product), class: 'cart-remove' %>&nbsp;|<%= button_to "Delete", product_path(product), method: :delete , class: 'cart-remove text' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No products listed yet.</p>
<% end %>

app/views/seller_dashboard/orders.html.erb
    <div class="body" style="top:0; position:absolute;">

<h1 class="cart-head">Orders for Your Products</h1>

<% if @orders.present? %>
<table id="customers">
  <thead>
    <tr>
      <th>Order ID</th>
      <th>User Mobile</th>
      <th>Shipping Address</th>
      <th>Order Items</th>
      <th>Ordered on</th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= order.mobile %></td>
        <td><%= order.address %></td>
        <td>
          <ul>
            <% order.order_items.each do |item| %>
              <p>
                <%= item.product.product_name %> - Quantity: <%= item.quantity %>
              </p>
            <% end %>
          </ul>
        </td>
        <td><%= order.created_at.strftime('%d %b %Y') %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>No orders found.</p>
<% end %>
</div>