config/routes.rb
Rails.application.routes.draw do
  get 'error/index'
  get 'profile/profile'
  post 'profile_update', to: 'profile#profile_update', as: :profile_update


  mount Notifications::Engine => "/notifications"


  get 'seller_dashboard/index'
  get 'seller_dashboard/orders'
  
  resources :carts, only: [:index]
  get 'add_to_cart/:product_id', to: 'carts#add_to_cart', as: 'add_to_cart'
  patch 'update_quantity/:id', to: 'carts#update_quantity', as: 'update_quantity'
  get 'remove_from_cart/:id', to: 'carts#remove_from_cart', as: 'remove_from_cart'
  post 'checkout', to: 'carts#checkout', as: 'checkout'


  resources :products do
    post 'review', on: :member, to: 'products#create_review'
  end

  get 'my_question/index'
  resources :live_feeds do
    resources :answers
  end



  resources :live_feeds do
    member do
      get "like" => "live_feeds#like"
      get "likes" => "live_feeds#likes"

    end
  end


  get 'my_questions/question'
  root to: "home#index"
  post '/home/send_location', to: 'home#send_location'


  devise_for :user, controllers:{ registrations:'user/registrations'}

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :live_feed ,  foreign_key: "live_feed_id" 
  belongs_to :user

  after_commit :create_notification, on: :create

  private
  
  def create_notification
    Notification.create do |notification|
      notification.notify_type = 'post'
      notification.actor = self.user
      notification.user=self.live_feed.user
      notification.target=self
      notification.second_target= self.live_feed
    end
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    belongs_to :product
    has_many :cart_items
  end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :live_feed
end

app/models/live_feed.rb
class LiveFeed < ApplicationRecord
    has_many :answers, dependent: :destroy
    has_many :likes, dependent: :destroy
    belongs_to :user
    has_one_attached :post_image
    acts_as_votable
    
    validates :post_image, presence: true
    validates :question_body, presence: true, length: { minimum: 10 }

    after_create_commit { broadcast_prepend_to 'live_feed_channel', target: 'live_feeds' }
    
end

app/models/notification.rb
# Auto generate with notifications gem.
class Notification < ActiveRecord::Base
  include Notifications::Model

  # Write your custom methods...
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy
  validates :address, presence: true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product 
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_one_attached :product_image
  has_many :carts , dependent: :destroy
  has_many :order_items, dependent: :destroy
  has_many :reviews, dependent: :destroy


  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "price", "product_description", "product_name", "quantity", "updated_at", "user_id"]
  end
  
end

app/models/profile_image.rb
class ProfileImage < ApplicationRecord
    belongs_to :user
    has_one_attached :image
  end
  

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user
  end
  

app/models/user.rb
class User < ApplicationRecord
  has_many :live_feeds
  has_many :products , dependent: :destroy
  has_many :carts
  has_many :orders, dependent: :destroy
  has_one :profile_image, dependent: :destroy
  has_many :reviews
  acts_as_voter


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



         validates :mobile, phone: { possible: true, allow_blank: true, types: [:voip, :mobile], country_specifier: -> (phone) { 'IN' } }

end

app/controllers/live_feeds_controller.rb
class LiveFeedsController < ApplicationController
  before_action :set_live_feed, only: %i[ show edit update destroy like likes ]




  # GET /live_feeds or /live_feeds.json
  def index
    if user_signed_in?
    @live_feeds = LiveFeed.all
    @live_feed = LiveFeed.new

    @latitude = session[:latitude]
    @longitude = session[:longitude]

      begin
       respo = HTTParty.get("https://api.openweathermap.org/data/2.5/weather?lat=#{@latitude}&lon=#{@longitude}&appid=d9ac7e81afaa607af356f9ce0db02af2")
       @weather =  JSON.parse(respo.body)

      rescue HTTParty::Error => e
       @error_message = "Failed to fetch weather data: #{e.message}"
      end

  else 
    redirect_to main_app.error_index_path
  end
  end

  # GET /live_feeds/1 or /live_feeds/1.json
  def show
    @live_feed = LiveFeed.find(params[:id])
    @answer = Answer.new
  end

  # GET /live_feeds/new
  def new
    @live_feed = LiveFeed.new
  end

  # GET /live_feeds/1/edit
  def edit
  end

  # POST /live_feeds or /live_feeds.json
  def create
    @live_feed = LiveFeed.new(live_feed_params)
    @live_feed.asked_by = current_user.id
    @live_feed.user_id = current_user.id


    respond_to do |format|
      if @live_feed.save
        format.html { redirect_to live_feeds_url, notice: "Live feed was successfully created." }
        format.json { render :show, status: :created, location: @live_feed }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @live_feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /live_feeds/1 or /live_feeds/1.json
  def update
    respond_to do |format|
      if @live_feed.update(live_feed_params)
        format.html { redirect_to live_feed_url(@live_feed), notice: "Live feed was successfully updated." }
        format.json { render :show, status: :ok, location: @live_feed }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @live_feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /live_feeds/1 or /live_feeds/1.json
  def destroy
      @live_feed.destroy!
      redirect_to live_feeds_url
  end


  def like
    if !current_user.liked? @live_feed
      @live_feed.liked_by current_user
    elsif current_user.liked? @live_feed
      @live_feed.unliked_by current_user
    end
    respond_to do |format|
      format.html { redirect_to live_feed_path }
      format.json { render json: { status: 'success' } }
    end
  end

  def likes
    if !current_user.liked? @live_feed
      @live_feed.liked_by current_user
    elsif current_user.liked? @live_feed
      @live_feed.unliked_by current_user
    end
    respond_to do |format|
      format.html { redirect_to live_feeds_path }
      format.json { render json: { status: 'success' } }
    end
  end






  private
    def set_live_feed
      @live_feed = LiveFeed.find(params[:id])
    end

    def live_feed_params
      params.require(:live_feed).permit(:post_image, :question_body, :asked_by)
    end
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/error_helper.rb
module ErrorHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/learning_helper.rb
module LearningHelper
end

app/helpers/live_feeds_helper.rb
module LiveFeedsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/live_feeds/_form.html.erb
<%= form_with(model: live_feed) do |form| %>
  <% if live_feed.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(live_feed.errors.count, "error") %> prohibited this live_feed from being saved:</h2>

      <ul>
        <% live_feed.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-cont">

  <div class="question-send">
    <%= form.file_field :post_image,placeholder: "upload the image",class:"question-title input" %>

    <%= form.text_area :question_body,placeholder: "Question Body",class:"question-body input" %>
  </div>

  <div>
    <%= form.submit 'Ask' , class:'send' %>
  </div>
  </div>

<% end %>

app/views/live_feeds/_live_feed.html.erb
<div class="question" id="live_feed_<%= live_feed.id %>">
  <div class="profile-info-post">
    <div>
      <% if live_feed.user.profile_image&.image&.attached? %>
        <%= image_tag(live_feed.user.profile_image.image, class: "pro_image p-i") %>
      <% else %>
        <%= image_tag "user.png", class: "pro_image" %>
      <% end %>
    </div>
    <div class="post-user-info">
      <p><%= live_feed.user.username %> </p>|
      <p><%= live_feed.user.account_type %> </p>
    </div>
  </div>
  <p class='q-body'><%= live_feed.question_body %></p>
  <% if live_feed.post_image.attached? %>
    <%= image_tag(live_feed.post_image, class: "post-file") %>
  <% end %>

  <p class="time"><%= live_feed.created_at.strftime('%d %b') %></p>
  <br>
  <div class="like-ans">
    <div class="like-feature">
    <span class="likes-count"><%= live_feed.get_upvotes.size %></span>
    <%= link_to likes_live_feed_path(live_feed) do %>
      <i class="fa fa-heart" id="like-btn-<%= live_feed.id %>"></i>
    <% end %>
  </div>
    <%= link_to live_feed, class: 'link' do %>
      <p style="margin-top:18px;"><%= live_feed.answers.count %> Answers</p>
    <% end %>
  </div>
</div>

<% if current_user.liked?(live_feed) %>
  <script>
    document.getElementById('like-btn-<%= live_feed.id %>').style.color = "red";
  </script>
<% end %>

app/views/live_feeds/edit.html.erb
<div class="container"></div>

<h1>Edit live feed</h1>

<%= render "form", live_feed: @live_feed %>

<br>

<div>
  <%= link_to "Show this live feed", @live_feed %> |
  <%= link_to "Back to live feeds", live_feeds_path %>
</div>

app/views/live_feeds/index.html.erb
<%
=begin%>
 <p style="color: green;position:absolute"><%= notice %></p> 
<%
=end%>



<%= stylesheet_link_tag "live_feed" %>

<body style="overflow: hidden;">
<div class="feed-container" >
<div id="live_feeds">
  <%= render @live_feeds %>
</div>
<div id="weather">
 <%= render "weather_forcast", weather: @weather %>  
</div>
</div>
<div class="ask_question">
<%= render "form", live_feed: @live_feed %>
</div>
</body>

app/views/live_feeds/new.html.erb
<h1>New live feed</h1>

<%= render "form", live_feed: @live_feed %>

<br>

<div>
  <%= link_to "Back to live feeds", live_feeds_path %>
</div>

app/views/live_feeds/show.html.erb
 
 
    <div class="body" style="top:0; position:absolute;">
  <%= link_to "Back", live_feeds_path , class:"to-feed" %>
<div class="question-answer">
<p style="color: green" class="toast"><%= notice %></p>

   <div class="question q-a">

 <%if current_user.id == @live_feed.asked_by%> 

   <div class="option">
  <%= link_to image_tag('edit.png',class:"edit"), edit_live_feed_path(@live_feed) %> 
  <%= button_to image_tag('delete.png',class:"edit"), @live_feed,method: :delete %>
</div>

 <%end%> 

  <div class="profile-info-post">
  <div>
  <% if @live_feed.user.profile_image&.image&.attached? %>
       <%= image_tag(@live_feed.user.profile_image.image, class:"pro_image p-i")%>
  <% else%>
       <%= image_tag "user.png" , class:"pro_image"%>
    <% end %>
       </div>
       <div class="post-user-info" >
       <p><%= @live_feed.user.username%> </p>|
       <p><%= @live_feed.user.account_type%> </p>
       </div>
       </div>
           <p class='q-body' style="text-align: start;"><%= @live_feed.question_body %></p>
           <% if @live_feed.post_image.attached? %>
  <%= image_tag(@live_feed.post_image, class:"post-file post-ans-file") %>
<% end %>
  <div class="like-ans">
    <div class="like-feature">
    <span class="likes-count"><%= @live_feed.get_upvotes.size %></span>
    <%= link_to like_live_feed_path(@live_feed) do %>
      <i class="fa fa-heart" id="like-btn"></i>
    <% end %>
  </div>

      <p class="link" style="margin-top:18px;"><%= @live_feed.answers.count %> Answers</p>

  </div>

   <p class="time"> <%= @live_feed.created_at.strftime('%d %b') %></p>
    </div>


 <div class="ans">
<% @live_feed.answers.each do |ans| %>
<div class="question">
 <div class="profile-info-post" style="color:black">
  <div>
  <% if @live_feed.user.profile_image&.image&.attached? %>
       <%= image_tag(@live_feed.user.profile_image.image, class:"pro_image p-i")%>
  <% else%>
       <%= image_tag "user.png" , class:"pro_image"%>
    <% end %>
       </div>
       <div class="post-user-info" >
       <p><%= @live_feed.user.username%> </p>|
       <p><%= @live_feed.user.account_type%> </p>
       </div>
       </div>
  <p class="q-body ans-body">
    <%= ans.answer_body %>
  </p>
    <p class="time" style="padding-top:5px;color:black;"><%= ans.created_at.strftime("%d %b")%></p>
  </p>
    <% if current_user.id == ans.user.id %>
   <div class="option">
      <%= link_to image_tag('edit.png', class: "edit"), edit_live_feed_answer_path(@live_feed, ans) %>
      <%= button_to image_tag('delete.png', class: "edit"), live_feed_answer_path(@live_feed, ans), method: :delete%>
  </div>
    <% end %>
  </div>
<% end %>
</div>




<%= form_with(model: [@live_feed, @answer]) do |form| %>
<div class="ans-que">
  <p>
    <%= form.text_area :answer_body ,placeholder: "Answer the Question",class:"question-body input" %>
  </p>
  <p>
    <%= form.submit "Answer", class:"answer-q" %>
  </p>
 </div>

<% end %>

</div>
</div>
<% if current_user.liked?(@live_feed) %>
  <script>
    document.getElementById('like-btn').style.color = "red";
  </script>
<% end %>