config/routes.rb
Rails.application.routes.draw do
  get 'error/index'
  get 'profile/profile'
  post 'profile_update', to: 'profile#profile_update', as: :profile_update


  mount Notifications::Engine => "/notifications"


  get 'seller_dashboard/index'
  get 'seller_dashboard/orders'
  
  resources :carts, only: [:index]
  get 'add_to_cart/:product_id', to: 'carts#add_to_cart', as: 'add_to_cart'
  patch 'update_quantity/:id', to: 'carts#update_quantity', as: 'update_quantity'
  get 'remove_from_cart/:id', to: 'carts#remove_from_cart', as: 'remove_from_cart'
  post 'checkout', to: 'carts#checkout', as: 'checkout'


  resources :products do
    post 'review', on: :member, to: 'products#create_review'
  end

  get 'my_question/index'
  resources :live_feeds do
    resources :answers
  end



  resources :live_feeds do
    member do
      get "like" => "live_feeds#like"
      get "likes" => "live_feeds#likes"

    end
  end


  get 'my_questions/question'
  root to: "home#index"
  post '/home/send_location', to: 'home#send_location'


  devise_for :user, controllers:{ registrations:'user/registrations'}

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :live_feed ,  foreign_key: "live_feed_id" 
  belongs_to :user

  after_commit :create_notification, on: :create

  private
  
  def create_notification
    Notification.create do |notification|
      notification.notify_type = 'post'
      notification.actor = self.user
      notification.user=self.live_feed.user
      notification.target=self
      notification.second_target= self.live_feed
    end
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    belongs_to :product
    has_many :cart_items
  end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :live_feed
end

app/models/live_feed.rb
class LiveFeed < ApplicationRecord
    has_many :answers, dependent: :destroy
    has_many :likes, dependent: :destroy
    belongs_to :user
    has_one_attached :post_image
    acts_as_votable
    
    validates :post_image, presence: true
    validates :question_body, presence: true, length: { minimum: 10 }

    after_create_commit { broadcast_prepend_to 'live_feed_channel', target: 'live_feeds' }
    
end

app/models/notification.rb
# Auto generate with notifications gem.
class Notification < ActiveRecord::Base
  include Notifications::Model

  # Write your custom methods...
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy
  validates :address, presence: true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product 
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_one_attached :product_image
  has_many :carts , dependent: :destroy
  has_many :order_items, dependent: :destroy
  has_many :reviews, dependent: :destroy


  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "price", "product_description", "product_name", "quantity", "updated_at", "user_id"]
  end
  
end

app/models/profile_image.rb
class ProfileImage < ApplicationRecord
    belongs_to :user
    has_one_attached :image
  end
  

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user
  end
  

app/models/user.rb
class User < ApplicationRecord
  has_many :live_feeds
  has_many :products , dependent: :destroy
  has_many :carts
  has_many :orders, dependent: :destroy
  has_one :profile_image, dependent: :destroy
  has_many :reviews
  acts_as_voter


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



         validates :mobile, phone: { possible: true, allow_blank: true, types: [:voip, :mobile], country_specifier: -> (phone) { 'IN' } }

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy create_review ]

  # GET /products or /products.json
  def index
    if user_signed_in?
    @q = Product.ransack(params[:q])
    @products=@q.result(distinct:true)
   # @products = Product.all
  else 
    redirect_to main_app.error_index_path
  end
  end

  # GET /products/1 or /products/1.json
  def show
    @reviews = @product.reviews
    @average_rating = @reviews.average(:rating).to_f.round(1).clamp(0, 5)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id if user_signed_in?
    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy!

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end




  def create_review
    @review = @product.reviews.new(review_params)
    @review.user = current_user

    respond_to do |format|
      if @review.save
        format.html { redirect_to @product, notice: "Review was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :show, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end

  end




  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:product_name, :product_image, :price, :product_description, :quantity)
    end

    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/error_helper.rb
module ErrorHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/learning_helper.rb
module LearningHelper
end

app/helpers/live_feeds_helper.rb
module LiveFeedsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/products/_form.html.erb
<style>
.checkout-btn{
  width:10rem;
  margin-left:10px;
}
</style>


<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="form">
  <div>
    <%= form.label :product_name, style: "display: block",class:"label" %>
    <%= form.text_field :product_name,class:"input" %>
  </div>

  <div>
    <%= form.label :product_image, style: "display: block",class:"label" %>
    <%= form.file_field :product_image ,class:"input" %>
  </div>

  <div>
    <%= form.label :price, style: "display: block",class:"label" %>
    <%= form.text_field :price ,class:"input" %>
  </div>

  <div>
    <%= form.label :product_description, style: "display: block",class:"label" %>
    <%= form.text_area :product_description,class:"input descr" %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block",class:"label" %>
    <%= form.number_field :quantity,class:"input" %>
  </div>

  <div>
    <%= form.submit class:"checkout-btn" %>
  </div>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Product name:</strong>
    <%= product.product_name %>
  </p>

  <p>
    <strong>Product image:</strong>
    <%= product.product_image %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Product description:</strong>
    <%= product.product_description %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= product.quantity %>
  </p>

  <p>
    <strong>User:</strong>
    <%= product.user_id %>
  </p>

</div>

app/views/products/_review.html.erb
<div class="rating-star">
<span class="fa fa-star rate fr"></span>
<span class="fa fa-star rate fr"></span>
<span class="fa fa-star rate fr"></span>
<span class="fa fa-star rate fr"></span>
<span class="fa fa-star rate fr"></span>
</div>
<div class="avg-rating">
<div style="line-height:2.3em"><%= render "show_review", rating: @average_rating %></div>
<h3 style="line-height:0.1em"><%= @average_rating %>/5.0</h3>
</div>


<div class="comm">
<%= form_with(model: [@product, @reviews], url: review_product_path(@product), local: true) do |form| %>
  <%= form.hidden_field :rating, value: 0, id: 'rating-value' %>
  <%= form.text_area :comment, placeholder: "Comment", class: "question-body input com-input",required: true  %>
  <%= form.submit 'Submit Rating',class:"com-btn" %>
<% end %>
</div>

<script>
    const stars = document.querySelectorAll('.fr');
    
    stars.forEach((star, index) => {
        star.addEventListener('click', () => {
            stars.forEach(s => s.classList.remove('checked'));
            
            for (let i = 0; i <= index; i++) {
                stars[i].classList.add('checked');
            }
    const checkedStars = document.querySelectorAll('.checked').length;
    document.getElementById("rating-value").value= checkedStars;
        });
    });

</script>

app/views/products/_show_review.html.erb
<% if @average_rating <1%>
<div class="rating-star">
<span class="fa fa-star rate"></span>
<span class="fa fa-star rate"></span>
<span class="fa fa-star rate"></span>
<span class="fa fa-star rate"></span>
<span class="fa fa-star rate"></span>
</div>
<% end %>


<% if @average_rating >0 && @average_rating <2 %>
<div class="rating-star">
<span class="fa fa-star rate checked"></span>
<span class="fa fa-star rate"></span>
<span class="fa fa-star rate"></span>
<span class="fa fa-star rate"></span>
<span class="fa fa-star rate"></span>
</div>
<% end %>

<% if @average_rating >=2 && @average_rating <3 %>
<div class="rating-star">
<span class="fa fa-star rate checked"></span>
<span class="fa fa-star rate checked"></span>
<span class="fa fa-star rate"></span>
<span class="fa fa-star rate"></span>
<span class="fa fa-star rate"></span>
</div>
<% end %>

<% if @average_rating >=3 && @average_rating <4 %>
<div class="rating-star">
<span class="fa fa-star rate checked"></span>
<span class="fa fa-star rate checked"></span>
<span class="fa fa-star rate checked"></span>
<span class="fa fa-star rate"></span>
<span class="fa fa-star rate"></span>
</div>
<% end %>

<% if @average_rating >=4 && @average_rating <5 %>
<div class="rating-star">
<span class="fa fa-star rate checked"></span>
<span class="fa fa-star rate checked"></span>
<span class="fa fa-star rate checked"></span>
<span class="fa fa-star rate checked"></span>
<span class="fa fa-star rate"></span>
</div>
<% end %>

<% if @average_rating == 5 %>
<div class="rating-star">
<span class="fa fa-star rate checked"></span>
<span class="fa fa-star rate checked"></span>
<span class="fa fa-star rate checked"></span>
<span class="fa fa-star rate checked"></span>
<span class="fa fa-star rate checked"></span>
</div>
<% end %>

app/views/products/edit.html.erb
<div class="container">

<h1 class="new-head">Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

</div>

app/views/products/index.html.erb
    <div class="body" style="top:0; position:absolute;">
<div class="store">
<p class="toast" style="color: green"><%= notice %></p>

<% if current_user.account_type != "student"%>
<div class="add-product">
<%= link_to "Add product", new_product_path,class:"link btn" %>
</div>
<% end %>

<%= search_form_for @q, url: products_path do |f| %>
  <div class="search">
  <div>
    <%= f.text_field :product_name_cont , placeholder:"Search",class:"input input-search"%>
  </div>
  <div>
    <%= f.submit "Search",class:"search-btn" %>
  </div>
  </div>
<% end %>

<div id="products">
  <% @products.each do |product| %>
  <div class="product-card">
  <%= link_to  product, class: 'link' do %>
     <% if product.product_image.attached? %>
  <%= image_tag product.product_image , class:"product_image" %>
<% end %>
<p class="product-name"><%= product.product_name%></p>
<p class="product-price"><%= number_to_currency(product.price,unit:'₹',precision:2)%>
</p>

  <% end %>
</div>
  <% end %>
</div>
</div>
</div>

app/views/products/new.html.erb
<div class="container">
<h1 class="new-head">New product</h1>


<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>
</div>

app/views/products/show.html.erb
<p class="toast" style="color: green"><%= notice %></p>
    <div class="body" style="top:0; position:absolute;">
<div class="show">
  <%= link_to "Back", products_path,class:"back show-back" %>
<div class="show-options">
<% if current_user.id == @product.user_id%>
  <%= link_to image_tag("pen.png",class:"show-edit"), edit_product_path(@product) %>
  <%= button_to image_tag("delete.png",class:"show-delete"), @product, method: :delete %>
  <% end %>
</div>

<div class="show-product">
<div>
     <% if @product.product_image.attached? %>
  <%= image_tag @product.product_image , class:"show_image" %>
<% end %>
</div>
<hr>
<div class="show-text">
<h1 class="show-name"><%= @product.product_name%></h1>
<p class="show-description"><%= @product.product_description%></p>
<div>seller: <%= @product.user.username%> | <%= @product.user.email%>    </div>
<h4 class="show-price">Price: Rs <%= @product.price%></h4>
<div class="add-to-cart"><%= link_to 'Add to Cart', add_to_cart_path(product_id: @product.id), method: :post %></div>
</div>

</div>
</div>

<div class="comments-show ans-que">
  <% @reviews.each do |review| %>
<div class="review">
  <div class="com-user-info">
 <p style="padding-left:15px"><%= review.user.username %></p>
 </div>
 <h4 class="comment" style="padding-left:15px"> <%= review.comment %> </h4>
    <p class="posted-on"><%= review.created_at.strftime('%d %b') %></p>
    </div>
  <% end %>
</div>
<%= render "review" %>
</div>